{% set name = "flake8-import-order" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4209620e63d3c6f4241ab7b0ebd4cdd29299edb96f145ebe95d3911910037fa3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pycodestyle
    - flake8
    - setuptools

test:
  requires:
    - python {{ python_min }}
  commands:
    - flake8 --version
  imports:
    - flake8_import_order

about:
  home: https://github.com/PyCQA/flake8-import-order
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: COPYING
  summary: A flake8 and Pylama plugin that checks the ordering of your imports.

  description: |
    A flake8 and Pylama plugin that checks the ordering of your imports.
    In general stdlib comes first, then 3rd party, then local packages,
    and that each group is individually alphabetized, see Configuration
    section for details. It will not check anything else about the
    imports. Merely that they are grouped and ordered correctly. This
    plugin is under somewhat active development and is heavily influenced
    by the personal preferences of the developers of cryptography. Expect
    seemingly random changes and configuration changes as we figure out
    how it should work.
  dev_url: https://github.com/PyCQA/flake8-import-order

extra:
  recipe-maintainers:
    - dopplershift
