travis:
  secure:
    BINSTAR_TOKEN: D+o79rjzYTF7dgQeKCRHUc9g76sX93ZIR7rUJAyMinTIW2hdr60hYQfbsvfCJEcBnmczpMqnop4+lycV7XY6ZHgB2uiUQsWlg2jm1tCwUa127XIO4wOZfMeN0O+8O7EagIzc64twnfIEOARrS+YsEkAw/APGbuG1cji60M0+YipRnj0acescf7c3cqcXeUMNf02jWmB8IcfVQMlATzMLG/2uaOfQoc/SD4uuDM8aXHr/oL2S659JmnM2neDZWdkuMNBPT8jBmxDwumpptrKiZB9DBQaustZgslsi6SfKeXxDPW46g6wtK4KKb0CsogG5rZ10rNDB0BL4U92RX9V9hL6wCoazGBaVQxO7TZ0RuUNJSlhrKsFkNNK7gHdin5S8zPzgYnovJD48UwtwWnvhc0LGZYkuZeHdz4lzZyWtw7X/H95bWyGEjFiWBbKva0hVzdCAkUfi5GD8yTyqNF1td20Mp/91z+XFlXxbwJIcDNuK7tECDoWSVsJc5kVy0FeRpq6WEFggdRnRb0wxv6hlsA3dmvDp+fPVJmvk2bu74CO2Y5V2KTkq56mN4113KJoyPnKRq7lwhEp1F5MBtNUWcYWh+sKvggV8oKqe0qyS2uiRB7Hzv7Np7/mEitDhlDyImsCoLzY6ymV2hEYnr7JwIQrCV4NNAUg5oY7zpZoLc0s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
